export const sel = {
    simpan_text_pattern: /^\s*simpan\s*$/i,
    simpan_button_selectors: [
        'button[type="submit"].w-fill.btn-fill-primary',
        'button[type="submit"].btn-fill-primary',
        'button[type="submit"]',
        "button"
    ],
    simpan_disabled_selector: "div.cursor-not-allowed",
    same_location_row_selector: "div.flex.gap-2",
    same_location_row_text_pattern: /lokasi sama dengan puskesmas/i,
    same_location_checkbox_selectors: [
        'input[name="sameLocation"][type="checkbox"]',
        'input#sameLocation[name="sameLocation"][type="checkbox"]',
        'input[name="sameLocation"]'
    ],
    same_location_visual_selector: "div#sameLocation.check",
    pelayanan_card_selector: "a, button, div",
    pelayanan_card_text_pattern: /pelayanan umum/i,
    search_filter_label_pattern: /^\s*nama\s*$/i,
    search_filter_option_nik_pattern: /^\s*nik\s*$/i,
    search_filter_trigger_selector: "div.h-\\[2\\.9rem\\].w-full.flex.gap-2.cursor-pointer",
    search_filter_label_selector: "span.line-clamp-2",
    search_filter_option_selector: "div.py-2.px-4.cursor-pointer.text-sm",
    search_input_nik_selectors: [
        "input#searchNik",
        'input[placeholder*="Masukkan NIK"]',
        'input[placeholder*="NIK"]'
    ],
    status_tab_selector: "div.cursor-pointer.px-3",
    status_tab_belum_pemeriksaan_pattern: /belum pemeriksaan/i,
    status_tab_sedang_pemeriksaan_pattern: /sedang pemeriksaan/i,
    status_tab_selesai_pemeriksaan_pattern: /selesai pemeriksaan/i,
    pelayanan_table_selector: ".table-individu-terdaftar table",
    pelayanan_row_selector: "tbody tr",
    mulai_button_pattern: /^\s*mulai\s*$/i,
    start_examination_button_pattern: /^\s*mulai pemeriksaan\s*$/i,
    examination_date_button_pattern: /^\s*tanggal pemeriksaan\s*$/i,
    send_report_button_pattern: /^\s*kirim rapor\b/i,
    send_report_button_selector: "div.btn-sent-report:has-text('Kirim Rapor'):not(:has-text('Lihat Rapor')), button.btn-sent-report:has-text('Kirim Rapor'):not(:has-text('Lihat Rapor'))",
    view_report_button_pattern: /^\s*lihat rapor\b/i,
    send_report_disabled_selector: ".cursor-not-allowed",
    send_report_modal_title_pattern: /kirim rapor anda/i,
    send_report_modal_selector: "div[role='dialog'], div[class*='shadow-gmail'], div.p-2",
    send_report_confirm_button_pattern: /^\s*kirim\s*$/i,
    finish_service_button_pattern: /^\s*selesaikan layanan\s*$/i,
    finish_service_modal_title_pattern: /data pemeriksaan akan dikunci/i,
    finish_service_modal_selector: "div[role='dialog'], div[class*='shadow-gmail'], div.p-2",
    finish_service_confirm_button_pattern: /^\s*konfirmasi\s*$/i,
    start_treatment_button_pattern: /^\s*mulai tatalaksana\s*$/i,
    exam_date_confirmation_title_pattern: /(konfirmasi|ubah)\s*tanggal\s*pemeriksaan/i,
    exam_date_confirmation_desc_pattern: /konfirmasi tanggal pemerikaan sebelum mulai input data/i,
    exam_date_confirmation_modal_selector: "div.p-2, div[role='dialog'], div[class*='shadow-gmail']",
    exam_date_calendar_selector: "div.relative.p-3.pt-2.border.rounded-md.bg-white.shadow-gmail",
    exam_date_save_button_pattern: /^\s*simpan\s*$/i,
    peserta_panel_pattern: /daftar peserta/i,
    nik_text_pattern: /\b\d{16}\b/g,
    wait: {
        element_visible_ms: 1500,
        short_delay_ms: 30,
        retry_delay_ms: 150,
        after_toggle_ms: 30,
        after_open_card_ms: 150,
        after_submit_ms: 150,
        after_tab_switch_ms: 150,
        after_start_examination_ms: 150,
        after_pick_exam_date_ms: 50,
        retry_loop_open_card_ms: 200,
        retry_loop_checkbox_ms: 150,
        click_timeout_ms: 2800,
        page_load_grace_ms: 150,
        network_settle_ms: 300
    },
    max_try: {
        retry_step: 6,
        save_profile: 3,
        submit_loop: 12
    }
};
